# Generated by Django 6.0.3 on 2026-04-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyplanning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='storyboard',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='outline',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='script',
            field=models.TextField(blank=True),
        ),
    ]
