# Generated by Django 6.0.3 on 2026-04-17 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyplanning', '0002_alter_character_description_alter_idea_storyboard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='scene',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='storyplanning.scene'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='character',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='storyplanning.character'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='idea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='storyplanning.idea'),
            preserve_default=False,
        ),
    ]
