# Generated by Django 6.0.3 on 2026-04-17 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyplanning', '0003_character_scene_image_character_image_idea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storyplanning.scene'),
        ),
        migrations.AlterField(
            model_name='image',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storyplanning.character'),
        ),
        migrations.AlterField(
            model_name='image',
            name='idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storyplanning.idea'),
        ),
    ]
