# Generated by Django 6.0.3 on 2026-04-24 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyplanning', '0006_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='idea',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='storyplanning.idea'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storyplanning.scene'),
        ),
    ]
