# Generated by Cursor on 2026-04-30

from django.db import migrations, models


def copy_character_scene_to_scenes(apps, schema_editor):
    '''Copy existing Character.scene links into new Character.scenes M2M rows.'''

    Character = apps.get_model('storyplanning', 'Character')
    for character in Character.objects.exclude(scene_id=None):
        character.scenes.add(character.scene_id)


def reverse_copy_character_scene_to_scenes(apps, schema_editor):
    '''On reverse migration, restore Character.scene from the first Character.scenes row.'''

    Character = apps.get_model('storyplanning', 'Character')
    for character in Character.objects.all():
        first_scene = character.scenes.first()
        character.scene_id = first_scene.pk if first_scene else None
        character.save(update_fields=['scene'])


class Migration(migrations.Migration):

    dependencies = [
        ('storyplanning', '0007_alter_image_idea_alter_image_scene'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='scenes',
            field=models.ManyToManyField(blank=True, related_name='characters', to='storyplanning.scene'),
        ),
        migrations.RunPython(copy_character_scene_to_scenes, reverse_copy_character_scene_to_scenes),
        migrations.RemoveField(
            model_name='character',
            name='scene',
        ),
    ]
