# Generated by Cursor on 2026-04-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storyplanning', '0008_character_scenes_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('scene_data', models.JSONField(blank=True, default=dict)),
                ('thumbnail_data_url', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storyplanning.character')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storyplanning.idea')),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storyplanning.scene')),
            ],
        ),
    ]
